
- name: install nvm 
  shell: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
- name: install node 13.8 
  shell: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
      nvm install 13.8


- name: install global packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  become_method: sudo
  with_items:
    - python3
    - npm
