- name: "copy app"
  ansible.builtin.copy:
        src: ~/artifact.tar.gz
        dest: ~/artifact.tar.gz



- name: Extract artifact
  ansible.builtin.shell: tar -xvf /home/ubuntu/artifact.tar.gz 



# - name: start the app
#   become: true
#   become_method: sudo
#   # become_user: root
#   ansible.builtin.shell: |
#     npm install
#     sudo npm i -g pm2
#     pm2 stop default
#     pm2 start npm -- start 
#     # nohup  pm2 start npm -- start &
#     pm2 start npm -- start  </dev/null >/dev/null 2>&1 &



- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/uda_app/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"