- name: "copy app"
  ansible.builtin.copy:
        src: ~/artifact.tar.gz
        dest: ~/artifact.tar.gz



- name: Extract artifact
  ansible.builtin.shell: tar -xvf /home/ubuntu/artifact.tar.gz 



- name: start the app
  become: true
  become_method: sudo
  # become_user: root
  ansible.builtin.shell: |
    npm install
    sudo npm i -g pm2
    pm2 stop default
    pm2 start npm -- start 
    # nohup  pm2 start npm -- start &
    pm2 start npm -- start  </dev/null >/dev/null 2>&1 &



