# - name: Install Python
#   become: true
#   become_method: sudo
#   become_user: root
#   raw: apt -y update && apt install -y python3
#   # changed_when: false

# # - name: "install python for Ansible."
# #   become: true
# #   raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
# #   changed_when: false

# - name: Install nodejs
#   become: true
#   become_method: sudo
#   become_user: root
#   raw: apt -y update && apt -y install  nodejs 
#   # changed_when: false

# - name: Install npm
#   become: true
#   become_method: sudo
#   become_user: root
#   raw: apt -y update && apt install -y   npm
#   # changed_when: false
  

- name: install node 
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.8 | sudo -E bash - &&sudo apt-get install -y nodejs

- name: install global packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  become_method: sudo
  with_items:
    - python3
    - npm



- name: Extract artifact
  ansible.builtin.shell: tar -xvf /home/ubuntu/artifact.tar.gz 



- name: Extract artifact
  ansible.builtin.shell: tar -xvf /home/ubuntu/artifact.tar.gz 
- name: start the app
  become: true
  become_method: sudo
  # become_user: root
  ansible.builtin.shell: |
    npm install
    sudo npm i -g pm2
    pm2 stop default
    pm2 start npm -- start 
    # nohup  pm2 start npm -- start &
    pm2 start npm -- start  </dev/null >/dev/null 2>&1 &

