- name: Install Python
  become: true
  become_method: sudo
  become_user: root
  raw: apt -y update && apt install -y python3
  changed_when: false

# - name: "install python for Ansible."
#   become: true
#   raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
#   changed_when: false

- name: Install nodejs
  become: true
  become_method: sudo
  become_user: root
  raw: apt -y update && apt -y install  nodejs 
  changed_when: false

- name: Install npm
  become: true
  become_method: sudo
  become_user: root
  raw: apt -y update && apt install -y   npm
  changed_when: false

- name: Extract artifact
  ansible.builtin.shell: tar -xvf /home/ubuntu/artifact.tar.gz 


 
#  artifact.tar.gz

# npm install
# pm2 stop default
# pm2 start npm -- start


- name: start the app
  become: true
  become_method: sudo
  become_user: root
  ansible.builtin.shell: |
              npm install;
              npm i -g pm2;
              pm2 stop default;
              # nohup  pm2 start npm -- start &
              daemonize -e /var/log/syslog -o /var/log/syslog  pm2 start npm -- start


